#!/bin/bash

BASE_URL=https://www.reddit.com/api/v1/authorize
CLIENT_ID=agzr4Pb-G6IQGf0au4AXnA
SCOPE=identity+read+mysubreddits
URI=telex://oauth
DURATION=permanent
STATE=testlex
TYPE=code

meson setup --reconfigure build
meson compile -C build
meson install -C build
AUTHORISATION_URL="$BASE_URL?client_id=$CLIENT_ID&response_type=$TYPE&state=$STATE&redirect_uri=$URI&duration=$DURATION&scope=$SCOPE" ./bin/telex
