from collections.abc import Callable as Callable
from gi.repository import Gdk, GdkPixbuf, Gtk

def load_image(img_path: str, alt_text: str, css_classes: list[str], css_provider: Gtk.CssProvider) -> Gtk.Picture: ...
def load_css(css_path) -> Gtk.CssProvider: ...
def add_style_context(widget: Gtk.Widget, css_provider: Gtk.CssProvider) -> None: ...
def add_style_contexts(widgets: list[Gtk.Widget], css_provider: Gtk.CssProvider) -> None: ...
def create_cursor(name: str) -> Gdk.Cursor | None: ...
def append_all(box: Gtk.Box, widgets: list[Gtk.Widget]) -> None: ...
def load_image_from_url_async(url: str, callback: Callable[[GdkPixbuf.Pixbuf | None], None]) -> None: ...
def create_image_widget(pixbuf) -> None: ...
