from _typeshed import Incomplete

class Reddit:
    domain: str
    system: Incomplete
    headers: Incomplete
    def __init__(self) -> None: ...
    def inject_token(self, token: str) -> None: ...
    def generate_access_token(self, code: str) -> dict[str, int | dict] | None: ...
    def retrieve_listings(self, category: str) -> dict[str, int | dict] | None: ...

class AzureClient:
    @classmethod
    def create_client(cls): ...
