from _typeshed import Incomplete
from gi.repository import Adw

class Telex(Adw.Application):
    def __init__(self) -> None: ...
    def do_activate(self) -> None: ...
    def on_quit_action(self, _action, _pspec) -> None: ...
    def on_about_action(self, _widget, _) -> None: ...
    def on_preferences_action(self, _widget, _) -> None: ...
    def create_action(self, name, callback, shortcuts: Incomplete | None = None) -> None: ...

def main(_version): ...
